# Generated by Django 3.0.2 on 2021-05-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210226_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='price',
        ),
        migrations.RemoveField(
            model_name='library',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='library',
            name='stock',
        ),
    ]
